name: Build and Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2.3.1
      - name: Jalankan Skrip
        env:
          # STARTUP : ${{ secrets.STARTUP  }}
          # SCAN: ${{ secrets.SCAN  }}
          # TEMPLATE_WEB: ${{ secrets.TEMPLATE_WEB  }}
        run: |
          git clone --single-branch --branch gh-pages https://github.com/iptv-org/iptv.git build
          # echo "$STARTUP " |  base64 -di > build/startup.sh
          # echo "$SCAN " | base64 -di  > build/scan.sh
          cd build
          bash startup.sh > /dev/null 2>&1
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          clean: true
          clean-exclude: |
            README.md
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: "[Bot] running at `date`"
 