name: Build and Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout another repo 🚚
        uses: actions/checkout@v4
        with:
          repository: iptv-org/iptv
          ref: gh-pages
          path: another

      # 以降確認用
      - name: Check the main repo 🚀
        working-directory: main
        run: |
          pwd
          ls -la
      - name: Check the another repo 🚚
        working-directory: another
        run: |
          pwd
          ls -la

  
