name: Build and Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repo 🐾
        uses: actions/checkout@v4
        with:
          ref: main
          path: local
      - name: Checkout remote repo 🚀
        uses: actions/checkout@v4
        with:
          repository: iptv-org/iptv
          ref: gh-pages
          path: remote
      - name: Copy files 🚚
        run: |
          cp -pr $GITHUB_WORKSPACE/remote/* $GITHUB_WORKSPACE/local/docs
          ls -la $GITHUB_WORKSPACE/local/docs
      - name: Commit & Push changes 🔥
        uses: Andro999b/push@v1.3
        with:
          directory: $GITHUB_WORKSPACE/local
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: 'github-actions[bot]@users.noreply.github.com'
          author_name: 'github-actions[bot]'
          message: 'chore: autopublish ${date}'
