name: Update list via xxx
on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  #毎周四0時実施

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 📋
        uses: actions/setup-node@v1
        with:
          node-version: "20.10.x"

      - name: Install m3u-linter 📋
        run: |
          npm install -g m3u-linter || true
#         m3u-linter -c ./M3u-linter.config.json ./work/playlist.m3u8

      - name: Install iptv-checker 📋
        run: |
          npm install -g iptv-checker || true
          sudo apt-get install -y ffmpeg

      # local
      - name: 1-0. Checkout local repo 🐾
        uses: actions/checkout@v4
        with:
          ref: main
          path: local

      # remote X
      - name: X-1. Checkout remote repo@fanmingming/live 🚀
        uses: actions/checkout@v4
        with:
          repository: fanmingming/live
          ref: main
          path: remote4
      - name: X-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          cp -rfp ${GITHUB_WORKSPACE}/remote4/XXX/*.m3u*     ${GITHUB_WORKSPACE}/local/work/XXX/
          tree -a
      - name: X-3. Check files 🔥
        run: |
          cp -rfp ${GITHUB_WORKSPACE}/local/work/*  ${GITHUB_WORKSPACE}/local/docs/m3u

#          dirwork=""
#          function read_dir(){
#            for file in `ls $1`
#            do
#              if [ -d $1"/"$file ]; then
#                echo "―folder: "$file
#                if [ ! -d ${GITHUB_WORKSPACE}/local/docs/m3u/$file ]; then
#                  mkdir -p ${GITHUB_WORKSPACE}/local/docs/m3u/$file
#                fi
#                dirwork=$file"/"
#                read_dir $1"/"$file
#              else
#                echo "⊥file: "$file
#                iptv-checker -o ${GITHUB_WORKSPACE}/local/output -p 100 -t 60000 $1"/"$file
#                cp -pr ${GITHUB_WORKSPACE}/local/output/online.m3u ${GITHUB_WORKSPACE}/local/docs/m3u/$dirwork$file
#              fi
#            done
#          }
#          read_dir ${GITHUB_WORKSPACE}/local/work

      - name: Commit & Push changes 🔥
        uses: Andro999b/push@v1.3
        with:
          branch: main
          directory: ${{ github.workspace }}/local/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: '🚀 auto publish by bot'
