name: Update all list
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'  #毎周六0時実施

jobs:
  update-all-list:
    runs-on: ubuntu-latest
    steps:

      # local
      - name: 1-0. Checkout local repo 🐾
        uses: actions/checkout@v4
        with:
          ref: main
          path: local

      # remote 1
      - name: 1-1. Checkout remote repo@iptv-org/iptv 🚀
        uses: actions/checkout@v4
        with:
          repository: iptv-org/iptv
          ref: gh-pages
          path: remote1
      - name: 1-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          cp -rfp ${GITHUB_WORKSPACE}/remote1/*  ${GITHUB_WORKSPACE}/local/work/
          ls -lat | sort -s -k 1,1


      # remote 2
      - name: 2-1. Checkout remote repo@Free-TV/IPTV 🚀
        uses: actions/checkout@v4
        with:
          repository: Free-TV/IPTV
          ref: master
          path: remote2
      - name: 2-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          cp -rfp ${GITHUB_WORKSPACE}/remote2/lists      ${GITHUB_WORKSPACE}/local/api/
          cp -rfp ${GITHUB_WORKSPACE}/remote2/playlists  ${GITHUB_WORKSPACE}/local/work/
          cp -rfp ${GITHUB_WORKSPACE}/remote2/*.m3u*     ${GITHUB_WORKSPACE}/local/work/
          ls -lat | sort -s -k 1,1


      # remote 3
      - name: 3-1 .Checkout remote repo@imDazui/Tvlist-awesome-m3u-m3u8 🚀
        uses: actions/checkout@v4
        with:
          repository: imDazui/Tvlist-awesome-m3u-m3u8
          ref: master
          path: remote3
      - name: 3-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          mkdir   ${GITHUB_WORKSPACE}/local/work/imDazui/
          cp -rfp ${GITHUB_WORKSPACE}/remote3/m3u/*.m3u*  ${GITHUB_WORKSPACE}/local/work/imDazui/
          ls -lat | sort -s -k 1,1


      # remote 4
      - name: 4-1. Checkout remote repo@fanmingming/live 🚀
        uses: actions/checkout@v4
        with:
          repository: fanmingming/live
          ref: main
          path: remote4
      - name: 4-2. Copy files 🚚
        run: |
          cd ${GITHUB_WORKSPACE}/local/work/
          rm -rf *
          mkdir   ${GITHUB_WORKSPACE}/local/work/tv/
          mkdir   ${GITHUB_WORKSPACE}/local/work/radio/
          cp -rfp ${GITHUB_WORKSPACE}/remote4/tv/m3u/*.m3u*     ${GITHUB_WORKSPACE}/local/work/tv/
          cp -rfp ${GITHUB_WORKSPACE}/remote4/radio/m3u/*.m3u*  ${GITHUB_WORKSPACE}/local/work/radio/
          ls -lat | sort -s -k 1,1


      - name: Commit & Push changes 🔥
        uses: Andro999b/push@v1.3
        with:
          branch: main
          directory: ${{ github.workspace }}/local/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: '🚀 auto publish by bot'
